### ISSUE TITLE
Problem in getting launched

### ISSUE THREAD

**Issue by dilawar** [TPVasconcelos/BoxParti#1]
Platform : openSUSE-42.1 . 

```
$ python --version
Python 2.7.12
$ python BoxParti.py 
Traceback (most recent call last):
  File "BoxParti.py", line 1495, in <module>
    app = BoxParti()
  File "BoxParti.py", line 55, in __init__
    frame = F(container, self)
  File "BoxParti.py", line 159, in __init__
    self.make_plot(frame)
  File "BoxParti.py", line 188, in make_plot
    self.toolbar = NavigationToolbar2TkAgg(self.canvas, container)
  File "/home1/dilawars/.local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 711, in __init__
    NavigationToolbar2.__init__(self, canvas)
  File "/home1/dilawars/.local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2739, in __init__
    self._init_toolbar()
  File "/home1/dilawars/.local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 772, in _init_toolbar
    self.pack(side=Tk.BOTTOM, fill=Tk.X)
  File "/usr/lib64/python2.7/lib-tk/Tkinter.py", line 1941, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: cannot use geometry manager pack inside .139731361039928.139731361059040.139731361096264 which already has slaves managed by grid
```

**Comment by dilawar** [comment]
Same issue on `Ubuntu-`14.04` .

**Comment by tpvasconcelos** [comment]
you need to be running on the 2TkAgg backend if I remember correctly. I just updated the BoxParti.py, see if my fix magically resolved your problem ;)
I am sorry I couldn't help much with this and sorry for the late reply!

**Comment by dilawar** [comment]
I just tried.

```
Traceback (most recent call last):
  File "BoxParti.py", line 1495, in <module>
    app = BoxParti()
  File "BoxParti.py", line 55, in __init__
    frame = F(container, self)
  File "BoxParti.py", line 159, in __init__
    self.make_plot(frame)
  File "BoxParti.py", line 188, in make_plot
    self.toolbar = NavigationToolbar2TkAgg(self.canvas, container)
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 711, in __init__
    NavigationToolbar2.__init__(self, canvas)
  File "/usr/lib64/python2.7/site-packages/matplotlib/backend_bases.py", line 2739, in __init__
    self._init_toolbar()
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 772, in _init_toolbar
    self.pack(side=Tk.BOTTOM, fill=Tk.X)
  File "/usr/lib64/python2.7/lib-tk/Tkinter.py", line 1941, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: cannot use geometry manager pack inside .139726828222224.139726828245216.139726828286752 which already has slaves managed by grid
```

**Comment by tpvasconcelos** [comment]
Ok just ran this on Ubuntu and got the same problem. It's because I am using grip and pack at the same time! Tkinter preferes that we use one only. For some reason it runs fine on mac. The solution to this is just use one method instead. Should be a simple fix since the problem only comes from the welcome page. I'm quite busy atm so I don't know how long it will be until I fix this but I will let you know. Feel free to give it a go! :-)

**Comment by tpvasconcelos** [comment]
**Taks:** Update tkinter geometry to use only `grip` or `pack` and not a combination of both.
